services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: resortdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: